In [ ]:
!wget -O train.csv https://www.dropbox.com/s/f4dzu371hgw1k9t/train.csv?dl=0

--2022-05-25 05:19:11--  https://www.dropbox.com/s/f4dzu371hgw1k9t/train.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.18, 2620:100:601b:18::a27d:812
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/f4dzu371hgw1k9t/train.csv [following]
--2022-05-25 05:19:11--  https://www.dropbox.com/s/raw/f4dzu371hgw1k9t/train.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc646366b4cbdea6838bd8d11cfd.dl.dropboxusercontent.com/cd/0/inline/Bl5zn6cBTM2jW7bdhcdfKfIe0rMBzKzPzT1TBzsVhAIySQCF_e-bTcC6O9SB4hMe6ntd6nFdSe0Oef4TfEVxxREeYVp38JpdhYReXQFNNhqmUtSEAkDd6hgmqUzw8dkd1eplvrrAIz9pQj6Bv7v5aGtMw-jb_qyXVB34KLuW5jPKvA/file# [following]
--2022-05-25 05:19:12--  https://uc646366b4cbdea6838bd8d11cfd.dl.dropboxusercontent.com/cd/0/inline/Bl5zn6cBTM2jW7bdhcdfKfIe0rMBzKzPzT1TBzsVhAIySQCF_e-bTcC6O9SB4hMe6ntd6nFd

In [ ]:
!wget -O test.csv https://www.dropbox.com/s/p5hk56v493psyd5/test.csv?dl=0

--2022-05-25 05:19:13--  https://www.dropbox.com/s/p5hk56v493psyd5/test.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.18, 2620:100:601b:18::a27d:812
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/p5hk56v493psyd5/test.csv [following]
--2022-05-25 05:19:13--  https://www.dropbox.com/s/raw/p5hk56v493psyd5/test.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucf35661a91d7fdd818c96bc7741.dl.dropboxusercontent.com/cd/0/inline/Bl6fbxnj-3xWf5S-9qXPmzI6SUBiP79HC80qv3X-I3Ome1GlUG0s9f3Vv_BqG3cqwQOWqiUEM7flOHUg5NEAd5OYfF908NGkyL2zkzq1K0UbMDKgluw7kyxcsNNiqzaRx2D8b291qLw51CGv4aDcW5mEYfZAA4IazgxQX68Uam-RYg/file# [following]
--2022-05-25 05:19:13--  https://ucf35661a91d7fdd818c96bc7741.dl.dropboxusercontent.com/cd/0/inline/Bl6fbxnj-3xWf5S-9qXPmzI6SUBiP79HC80qv3X-I3Ome1GlUG0s9f3Vv_BqG3cqwQOWqiUEM7f

In [ ]:
import pandas as pd

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [ ]:
train_df.dropna(inplace=True)
test_df.dropna(inplace=True)

In [ ]:
import numpy as np

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

non_numerical_columns = ['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction']

for i in non_numerical_columns:
    label_encoder.fit(train_df[i])
    train_df[i] = label_encoder.transform(train_df[i])

    label_encoder.fit(test_df[i])
    test_df[i] = label_encoder.transform(test_df[i])


train_df

Unnamed: 0      id  Gender  Customer Type  Age  Type of Travel  Class  \
0                0   70172       1              0   13               1      2   
1                1    5047       1              1   25               0      0   
2                2  110028       0              0   26               0      0   
3                3   24026       0              0   25               0      0   
4                4  119299       1              0   61               0      0   
...            ...     ...     ...            ...  ...             ...    ...   
103899      103899   94171       0              1   23               0      1   
103900      103900   73097       1              0   49               0      0   
103901      103901   68825       1              1   30               0      0   
103902      103902   54173       0              1   22               0      1   
103903      103903   62567       1              0   27               0      0   

        Flight Distance  Inflight wifi service  \
0                   460                      3   
1                   235                      3   
2                  1142                      2   
3                   562                      2   
4                   214                      3   
...                 ...                    ...   
103899              192                      2   
103900             2347                      4   
103901             1995                      1   
103902             1000                      1   
103903             1723                      1   

        Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                       4  ...                       5   
1                                       2  ...                       1   
2                                       2  ...                       5   
3                                       5  ...                       2   
4                                       3  ...                       3   
...                                   ...  ...                     ...   
103899                                  1  ...                       2   
103900                                  4  ...                       5   
103901                                  1  ...                       4   
103902                                  1  ...                       1   
103903                                  3  ...                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
0                      4                 3                 4                4   
1                      1                 5                 3                1   
2                      4                 3                 4                4   
3                      2                 5                 3                1   
4                      3                 4                 4                3   
...                  ...               ...               ...              ...   
103899                 3                 1                 4                2   
103900                 5                 5                 5                5   
103901                 3                 2                 4                5   
103902                 4                 5                 1                5   
103903                 1                 1                 4                4   

        Inflight service  Cleanliness  Departure Delay in Minutes  \
0                      5            5                          25   
1                      4            1                           1   
2                      4            5                           0   
3                      4            2                          11   
4                      3            3                           0   
...                  ...          ...                         ...   
103899                 3            2                           3   
103900              

In [ ]:
test_df

Unnamed: 0     id  Gender  Customer Type  Age  Type of Travel  Class  \
0               0  19556       0              0   52               0      1   
1               1  90035       0              0   36               0      0   
2               2  12360       1              1   20               0      1   
3               3  77959       1              0   44               0      0   
4               4  36875       0              0   49               0      1   
...           ...    ...     ...            ...  ...             ...    ...   
25971       25971  78463       1              1   34               0      0   
25972       25972  71167       1              0   23               0      0   
25973       25973  37675       0              0   17               1      1   
25974       25974  90086       1              0   14               0      0   
25975       25975  34799       0              0   42               1      1   

       Flight Distance  Inflight wifi service  \
0                  160                      5   
1                 2863                      1   
2                  192                      2   
3                 3377                      0   
4                 1182                      2   
...                ...                    ...   
25971              526                      3   
25972              646                      4   
25973              828                      2   
25974             1127                      3   
25975              264                      2   

       Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                      4  ...                       5   
1                                      1  ...                       4   
2                                      0  ...                       2   
3                                      0  ...                       1   
4                                      3  ...                       2   
...                                  ...  ...                     ...   
25971                                  3  ...                       4   
25972                                  4  ...                       4   
25973                                  5  ...                       2   
25974                                  3  ...                       4   
25975                                  5  ...                       1   

       On-board service  Leg room service  Baggage handling  Checkin service  \
0                     5                 5                 5                2   
1                     4                 4                 4                3   
2                     4                 1                 3                2   
3                     1                 1                 1                3   
4                     2                 2                 2                4   
...                 ...               ...               ...              ...   
25971                 3                 2                 4                4   
25972                 4                 5                 5                5   
25973                 4                 3                 4                5   
25974                 3                 2                 5                4   
25975                 1                 2                 1                1   

       Inflight service  Cleanliness  Departure Delay in Minutes  \
0                     5            5                          50   
1                     4            5                           0   
2                     2            2                           0   
3                     1            4                           0   
4                     2            4                           0   
...                 ...          ...                         ...   
25971                 5            4                           0   
25972                 5            4                           0   
25973              

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

In [ ]:
y_train = train_df['satisfaction'].values
y_test = test_df['satisfaction'].values

In [ ]:
X_train = train_df.iloc[:, 2:-1].values
X_test = test_df.iloc[:, 2:-1].values

In [ ]:
standard = preprocessing.StandardScaler()
standard.fit(X_train)
X_train_standard = standard.transform(X_train)
X_test_standard = standard.transform(X_test)

In [ ]:
perceptron_model = Perceptron()
perceptron_model.fit(X_train_standard, y_train)

Perceptron()

In [ ]:
y_pred = perceptron_model.predict(X_test_standard)
y_pred

array([1, 1, 0, ..., 0, 1, 0])

In [ ]:
y_test

array([1, 1, 0, ..., 0, 1, 0])

In [ ]:
accuracy_score(y_test, y_pred)

0.8270575058896227

In [ ]:
def RBF(X1, X2, d=3):
    return (1+np.dot(X1.T, X2)) ** d
    

In [ ]:
import time as t

In [ ]:
samples, features = X_train_standard.shape
alpha = np.zeros(samples)

start = t.time()
for iteration in range(1):
    for i in range(samples):
        if i%100 == 0:
            print(t.time() - start)
        k = np.zeros(samples)
        for j in range(samples):
            k[j] = RBF(X_train_standard[i], X_train_standard[j])

        if np.sign(np.sum(alpha * y_train * k)) != y_train[i]:
            alpha[i] += 1


In [ ]:
alpha

array([0., 0., 1., ..., 0., 0., 0.])